## Import important libraries

In [1]:
import pandas as pd
import sqlite3 as sql

## Make connection

In [2]:
conn = sql.connect("chinook.db")

def sql_query(q):
    return pd.read_sql_query(q, conn)

In [3]:
 sql_query("select * from sqlite_master")

,type,name,tbl_name,rootpage,sql
0,table,album,album,2,CREATE TABLE [album]\n(\n [album_id] INTEGE...
1,table,artist,artist,3,CREATE TABLE [artist]\n(\n [artist_id] INTE...
2,table,customer,customer,4,CREATE TABLE [customer]\n(\n [customer_id] ...
3,table,employee,employee,5,CREATE TABLE [employee]\n(\n [employee_id] ...
4,table,genre,genre,6,CREATE TABLE [genre]\n(\n [genre_id] INTEGE...
5,table,invoice,invoice,7,CREATE TABLE [invoice]\n(\n [invoice_id] IN...
6,table,invoice_line,invoice_line,8,CREATE TABLE [invoice_line]\n(\n [invoice_l...
7,table,media_type,media_type,9,CREATE TABLE [media_type]\n(\n [media_type_...
8,table,playlist,playlist,10,CREATE TABLE [playlist]\n(\n [playlist_id] ...
9,table,playlist_track,playlist_track,11,CREATE TABLE [playlist_track]\n(\n [playlis...
10,index,sqlite_autoindex_playlist_track_1,playlist_track,12,NaN
11,table,track,track,13,CREATE TABLE [track]\n(\n [track_id] INTEGE...
12,index,ifk_albumartist_id,album,16,CREATE INDEX [ifk_albumartist_id] ON [album] (...
13,index,ifk_customersupport_rep_id,customer,17,CREATE INDEX [ifk_customersupport_rep_id] ON [...
14,index,ifk_employeereports_to,employee,18,CREATE INDEX [ifk_employeereports_to] ON [empl...
15,index,ifk_invoicecustomer_id,invoice,19,CREATE INDEX [ifk_invoicecustomer_id] ON [invo...
16,index,ifk_invoice_lineinvoice_id,invoice_line,20,CREATE INDEX [ifk_invoice_lineinvoice_id] ON [...
17,index,ifk_invoice_linetrack_id,invoice_line,21,CREATE INDEX [ifk_invoice_linetrack_id] ON [in...
18,index,ifk_playlist_tracktrack_id,playlist_track,22,CREATE INDEX [ifk_playlist_tracktrack_id] ON [...
19,index,ifk_trackalbum_id,track,23,CREATE INDEX [ifk_trackalbum_id] ON [track] ([...
20,index,ifk_trackgenre_id,track,24,CREATE INDEX [ifk_trackgenre_id] ON [track] ([...
21,index,ifk_trackmedia_type_id,track,25,CREATE INDEX [ifk_trackmedia_type_id] ON [trac...
22,table,wishlist_track,wishlist_track,261,CREATE TABLE wishlist_track(\nwishlist_id Inte...
23,index,sqlite_autoindex_wishlist_track_1,wishlist_track,262,NaN
24,table,wishlist,wishlist,260,"CREATE TABLE ""wishlist"" (\n\t""whishlist_id""\tI..."
25,view,CUSTOMER_ABV2_90,CUSTOMER_ABV2_90,0,CREATE VIEW CUSTOMER_ABV2_90 as \n sele...
26,view,customer_get_90_dollars,customer_get_90_dollars,0,CREATE VIEW customer_get_90_dollars as\n Sel...
27,view,customer_usa,customer_usa,0,CREATE VIEW customer_usa as\n sele...
28,view,customer_gt_90_dollars,customer_gt_90_dollars,0,CREATE VIEW customer_gt_90_dollars as\n Sele...
29,view,city_redmond,city_redmond,0,CREATE VIEW city_redmond as\n sele...
30,view,CUSTOMER_ABV3_80,CUSTOMER_ABV3_80,0,CREATE VIEW CUSTOMER_ABV3_80 as \n sele...

## Check the table names

In [4]:
sql_query("select * from sqlite_master where type = 'table'")

,type,name,tbl_name,rootpage,sql
0,table,album,album,2,CREATE TABLE [album]\n(\n [album_id] INTEGE...
1,table,artist,artist,3,CREATE TABLE [artist]\n(\n [artist_id] INTE...
2,table,customer,customer,4,CREATE TABLE [customer]\n(\n [customer_id] ...
3,table,employee,employee,5,CREATE TABLE [employee]\n(\n [employee_id] ...
4,table,genre,genre,6,CREATE TABLE [genre]\n(\n [genre_id] INTEGE...
5,table,invoice,invoice,7,CREATE TABLE [invoice]\n(\n [invoice_id] IN...
6,table,invoice_line,invoice_line,8,CREATE TABLE [invoice_line]\n(\n [invoice_l...
7,table,media_type,media_type,9,CREATE TABLE [media_type]\n(\n [media_type_...
8,table,playlist,playlist,10,CREATE TABLE [playlist]\n(\n [playlist_id] ...
9,table,playlist_track,playlist_track,11,CREATE TABLE [playlist_track]\n(\n [playlis...
10,table,track,track,13,CREATE TABLE [track]\n(\n [track_id] INTEGE...
11,table,wishlist_track,wishlist_track,261,CREATE TABLE wishlist_track(\nwishlist_id Inte...
12,table,wishlist,wishlist,260,"CREATE TABLE ""wishlist"" (\n\t""whishlist_id""\tI..."

In [5]:
q = """select * from invoice 

"""
sql_query(q)

,invoice_id,customer_id,invoice_date,billing_address,billing_city,billing_state,billing_country,billing_postal_code,total,tax,subtotal
0,1,18,2017-01-03 00:00:00,627 Broadway,New York,NY,USA,10012-2612,15.84,0,15.84
1,2,30,2017-01-03 00:00:00,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,9.90,0,9.90
2,3,40,2017-01-05 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,1.98,0,1.98
3,4,18,2017-01-06 00:00:00,627 Broadway,New York,NY,USA,10012-2612,7.92,0,7.92
4,5,27,2017-01-07 00:00:00,1033 N Park Ave,Tucson,AZ,USA,85719,16.83,0,16.83
...,...,...,...,...,...,...,...,...,...,...,...
609,610,55,2020-12-21 00:00:00,421 Bourke Street,Sidney,NSW,Australia,2010,6.93,0,6.93
610,611,52,2020-12-27 00:00:00,202 Hoxton Street,London,None,United Kingdom,N1 5LH,1.98,0,1.98
611,612,33,2020-12-27 00:00:00,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,11.88,0,11.88
612,613,20,2020-12-29 00:00:00,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,8.91,0,8.91
613,614,53,2020-12-30 00:00:00,113 Lupus St,London,None,United Kingdom,SW1V 3EN,12.87,0,12.87

In [6]:
q = """select * from invoice where invoice_id = 1

"""
sql_query(q)

,invoice_id,customer_id,invoice_date,billing_address,billing_city,billing_state,billing_country,billing_postal_code,total,tax,subtotal
0,1,18,2017-01-03 00:00:00,627 Broadway,New York,NY,USA,10012-2612,15.84,0,15.84

In [7]:
q = """select * from invoice_line 
        where invoice_id == 1
"""
sql_query(q)

    invoice_line_id  invoice_id  track_id  unit_price  quantity
0                 1           1      1158        0.99         1
1                 2           1      1159        0.99         1
2                 3           1      1160        0.99         1
3                 4           1      1161        0.99         1
4                 5           1      1162        0.99         1
5                 6           1      1163        0.99         1
6                 7           1      1164        0.99         1
7                 8           1      1165        0.99         1
8                 9           1      1166        0.99         1
9                10           1      1167        0.99         1
10               11           1      1168        0.99         1
11               12           1      1169        0.99         1
12               13           1      1170        0.99         1
13               14           1      1171        0.99         1
14               15           1      1172        0.99         1
15               16           1      1173        0.99         1

In [8]:
q = "select * from track where track_id == 1158"
sql_query(q)

,track_id,name,album_id,media_type_id,genre_id,composer,milliseconds,bytes,unit_price
0,1158,Right Next Door to Hell,91,2,1,None,182321,3175950,0.99

## invoice_id, track_id, track_name, media_type name, quantity, unit_price  where invoice_id = 1

In [9]:
q = """select il.invoice_id, t.track_id, t.name track_name, m.name media_name, il.quantity,
        il.unit_price
        from invoice_line il
        inner join track t
        on 
        il.track_id = t.track_id
        inner join media_type m
        on 
        t.media_type_id = m.media_type_id
        where il.invoice_id == 1

"""

sql_query(q)

,invoice_id,track_id,track_name,media_name,quantity,unit_price
0,1,1158,Right Next Door to Hell,Protected AAC audio file,1,0.99
1,1,1159,Dust N' Bones,Protected AAC audio file,1,0.99
2,1,1160,Live and Let Die,Protected AAC audio file,1,0.99
3,1,1161,Don't Cry (Original),Protected AAC audio file,1,0.99
4,1,1162,Perfect Crime,Protected AAC audio file,1,0.99
5,1,1163,You Ain't the First,Protected AAC audio file,1,0.99
6,1,1164,Bad Obsession,Protected AAC audio file,1,0.99
7,1,1165,Back off Bitch,Protected AAC audio file,1,0.99
8,1,1166,Double Talkin' Jive,Protected AAC audio file,1,0.99
9,1,1167,November Rain,Protected AAC audio file,1,0.99
10,1,1168,The Garden,Protected AAC audio file,1,0.99
11,1,1169,Garden of Eden,Protected AAC audio file,1,0.99
12,1,1170,Don't Damn Me,Protected AAC audio file,1,0.99
13,1,1171,Bad Apples,Protected AAC audio file,1,0.99
14,1,1172,Dead Horse,Protected AAC audio file,1,0.99
15,1,1173,Coma,Protected AAC audio file,1,0.99

## invoice_id, track_id, track_name, artist_name, media_type_name, quantity, unit_price, where invoice_id = 1

In [10]:

q = """select il.invoice_id, t.track_id, t.name track_name,ar.name artist_name,
        m.name media_name, il.quantity, il.unit_price
        from invoice_line il
        inner join track t
        on 
        il.track_id = t.track_id
        inner join media_type m
        on 
        t.media_type_id = m.media_type_id
        inner join album al
        on 
        t.album_id = al.album_id
        inner join artist ar
        on
        al.artist_id = ar.artist_id
        
        where invoice_id == 1

"""

sql_query(q)

,invoice_id,track_id,track_name,artist_name,media_name,quantity,unit_price
0,1,1158,Right Next Door to Hell,Guns N' Roses,Protected AAC audio file,1,0.99
1,1,1159,Dust N' Bones,Guns N' Roses,Protected AAC audio file,1,0.99
2,1,1160,Live and Let Die,Guns N' Roses,Protected AAC audio file,1,0.99
3,1,1161,Don't Cry (Original),Guns N' Roses,Protected AAC audio file,1,0.99
4,1,1162,Perfect Crime,Guns N' Roses,Protected AAC audio file,1,0.99
5,1,1163,You Ain't the First,Guns N' Roses,Protected AAC audio file,1,0.99
6,1,1164,Bad Obsession,Guns N' Roses,Protected AAC audio file,1,0.99
7,1,1165,Back off Bitch,Guns N' Roses,Protected AAC audio file,1,0.99
8,1,1166,Double Talkin' Jive,Guns N' Roses,Protected AAC audio file,1,0.99
9,1,1167,November Rain,Guns N' Roses,Protected AAC audio file,1,0.99
10,1,1168,The Garden,Guns N' Roses,Protected AAC audio file,1,0.99
11,1,1169,Garden of Eden,Guns N' Roses,Protected AAC audio file,1,0.99
12,1,1170,Don't Damn Me,Guns N' Roses,Protected AAC audio file,1,0.99
13,1,1171,Bad Apples,Guns N' Roses,Protected AAC audio file,1,0.99
14,1,1172,Dead Horse,Guns N' Roses,Protected AAC audio file,1,0.99
15,1,1173,Coma,Guns N' Roses,Protected AAC audio file,1,0.99

## track_id, album title, artist name

In [11]:
q = """select t.track_id , al.title album_title, ar.name artist_name
        from track t
        inner join album al
        on
        t.album_id = al.album_id
        inner join artist ar
        on 
        al.artist_id = ar.artist_id

"""
sql_query(q)

,track_id,album_title,artist_name
0,1,For Those About To Rock We Salute You,AC/DC
1,6,For Those About To Rock We Salute You,AC/DC
2,7,For Those About To Rock We Salute You,AC/DC
3,8,For Those About To Rock We Salute You,AC/DC
4,9,For Those About To Rock We Salute You,AC/DC
...,...,...,...
3498,3499,Respighi:Pines of Rome,Eugene Ormandy
3499,3500,Schubert: The Late String Quartets & String Qu...,Emerson String Quartet
3500,3501,Monteverdi: L'Orfeo,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
3501,3502,Mozart: Chamber Music,Nash Ensemble
3502,3503,Koyaanisqatsi (Soundtrack from the Motion Pict...,Philip Glass Ensemble

## no_of_tracks_sale, album_name, artist_name

In [12]:
 

q = """select count(il.track_id) No_of_tracks, al.title album_name, ar.name artist_name
        from invoice_line il
        inner join track t
        on
        il.track_id = t.track_id
        inner join album al
        on
        t.album_id = al.album_id
        inner join artist ar
        on
        al.artist_id = ar.artist_id
        group by 2

"""
sql_query(q)

,No_of_tracks,album_name,artist_name
0,3,...And Justice For All,Metallica
1,74,20th Century Masters - The Millennium Collecti...,Scorpions
2,4,A Matter of Life and Death,Iron Maiden
3,7,A Real Dead One,Iron Maiden
4,3,A Real Live One,Iron Maiden
...,...,...,...
246,4,Walking Into Clarksdale,Page & Plant
247,7,War,U2
248,18,Warner 25 Anos,Antônio Carlos Jobim
249,3,Worlds,Aaron Goldberg
250,5,Zooropa,U2

# Top 5 track sale

In [13]:

q = """select count(il.track_id) No_of_tracks_sale, al.title album_name, ar.name artist_name
        from invoice_line il
        inner join track t
        on
        il.track_id = t.track_id
        inner join album al
        on
        t.album_id = al.album_id
        inner join artist ar
        on
        al.artist_id = ar.artist_id
        group by 2
        order by 1 DESC limit 5

"""
sql_query(q)

   No_of_tracks_sale            album_name       artist_name
0                187  Are You Experienced?      Jimi Hendrix
1                 96              Faceless          Godsmack
2                 93             Mezmerize  System Of A Down
3                 90              Get Born               JET
4                 83             The Doors         The Doors

In [14]:
q = """select * from employee
"""
sql_query(q)

,employee_id,last_name,first_name,title,reports_to,birthdate,hire_date,address,city,state,country,postal_code,phone,fax,email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2016-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2016-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2017-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2017-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2017-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com
5,6,Mitchell,Michael,IT Manager,1.0,1973-07-01 00:00:00,2016-10-17 00:00:00,5827 Bowness Road NW,Calgary,AB,Canada,T3B 0C5,+1 (403) 246-9887,+1 (403) 246-9899,michael@chinookcorp.com
6,7,King,Robert,IT Staff,6.0,1970-05-29 00:00:00,2017-01-02 00:00:00,590 Columbia Boulevard West,Lethbridge,AB,Canada,T1K 5N8,+1 (403) 456-9986,+1 (403) 456-8485,robert@chinookcorp.com
7,8,Callahan,Laura,IT Staff,6.0,1968-01-09 00:00:00,2017-03-04 00:00:00,923 7 ST NW,Lethbridge,AB,Canada,T1H 1Y8,+1 (403) 467-3351,+1 (403) 467-8772,laura@chinookcorp.com

In [15]:
q = """select title, employee_id, reports_to from employee
"""
sql_query(q)

                 title  employee_id  reports_to
0      General Manager            1         NaN
1        Sales Manager            2         1.0
2  Sales Support Agent            3         2.0
3  Sales Support Agent            4         2.0
4  Sales Support Agent            5         2.0
5           IT Manager            6         1.0
6             IT Staff            7         6.0
7             IT Staff            8         6.0

In [16]:

q = """select e.first_name, e.last_name , e.title Employee_Title, e.reports_to, e.employee_id
        from employee e
"""
sql_query(q)

  first_name last_name       Employee_Title  reports_to  employee_id
0     Andrew     Adams      General Manager         NaN            1
1      Nancy   Edwards        Sales Manager         1.0            2
2       Jane   Peacock  Sales Support Agent         2.0            3
3   Margaret      Park  Sales Support Agent         2.0            4
4      Steve   Johnson  Sales Support Agent         2.0            5
5    Michael  Mitchell           IT Manager         1.0            6
6     Robert      King             IT Staff         6.0            7
7      Laura  Callahan             IT Staff         6.0            8

## first and last name emp title id  reports_to

In [17]:
q = """select e.first_name ||" "|| e.last_name Full_name, e.title Employee_Title, e.reports_to, e.employee_id
        from employee e
"""
sql_query(q)

          Full_name       Employee_Title  reports_to  employee_id
0      Andrew Adams      General Manager         NaN            1
1     Nancy Edwards        Sales Manager         1.0            2
2      Jane Peacock  Sales Support Agent         2.0            3
3     Margaret Park  Sales Support Agent         2.0            4
4     Steve Johnson  Sales Support Agent         2.0            5
5  Michael Mitchell           IT Manager         1.0            6
6       Robert King             IT Staff         6.0            7
7    Laura Callahan             IT Staff         6.0            8

`Primary Key (PK):` Contains unique records, meaning each value in the Primary Key column is distinct and cannot be duplicated. It uniquely identifies each row in the table.

`Foreign Key (FK):` Can have multiple records because it refers to the Primary Key of another (or the same) table. Foreign Key values can be repeated, as multiple rows may reference the same record from the referenced table.

In [18]:
q = """select e1.first_name ||" "|| e1.last_name Full_name, e1.title Employee_Title,
        e1.reports_to, e1.employee_id,e2.first_name ||" "|| e2.last_name Supervisor_Name
        from employee e1
        left join employee e2
        on
        e1.reports_to = e2.employee_id
        
"""
sql_query(q)

,Full_name,Employee_Title,reports_to,employee_id,Supervisor_Name
0,Andrew Adams,General Manager,NaN,1,NaN
1,Nancy Edwards,Sales Manager,1.0,2,Andrew Adams
2,Jane Peacock,Sales Support Agent,2.0,3,Nancy Edwards
3,Margaret Park,Sales Support Agent,2.0,4,Nancy Edwards
4,Steve Johnson,Sales Support Agent,2.0,5,Nancy Edwards
5,Michael Mitchell,IT Manager,1.0,6,Andrew Adams
6,Robert King,IT Staff,6.0,7,Michael Mitchell
7,Laura Callahan,IT Staff,6.0,8,Michael Mitchell

In [19]:
q = """select e1.first_name ||" "|| e1.last_name Full_name, e1.title Employee_Title,
        e1.reports_to, e1.employee_id,e2.first_name ||" "|| e2.last_name Supervisor_Name
        from employee e1
        inner join employee e2
        on
        e1.reports_to = e2.employee_id
        
"""
sql_query(q)

,Full_name,Employee_Title,reports_to,employee_id,Supervisor_Name
0,Nancy Edwards,Sales Manager,1,2,Andrew Adams
1,Jane Peacock,Sales Support Agent,2,3,Nancy Edwards
2,Margaret Park,Sales Support Agent,2,4,Nancy Edwards
3,Steve Johnson,Sales Support Agent,2,5,Nancy Edwards
4,Michael Mitchell,IT Manager,1,6,Andrew Adams
5,Robert King,IT Staff,6,7,Michael Mitchell
6,Laura Callahan,IT Staff,6,8,Michael Mitchell

## Check customer table

In [20]:
q = """select * from customer
"""
sql_query(q)

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,0171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,NaN,Rilská 3174/6,Prague,NaN,Czech Republic,14300,+420 2 4177 0449,NaN,hholy@gmail.com,5
6,7,Astrid,Gruber,NaN,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,NaN,Austria,1010,+43 01 5134505,NaN,astrid.gruber@apple.at,5
7,8,Daan,Peeters,NaN,Grétrystraat 63,Brussels,NaN,Belgium,1000,+32 02 219 03 03,NaN,daan_peeters@apple.be,4
8,9,Kara,Nielsen,NaN,Sønder Boulevard 51,Copenhagen,NaN,Denmark,1720,+453 3331 9991,NaN,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
12,13,Fernanda,Ramos,NaN,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
17,18,Michelle,Brooks,NaN,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
19,20,Dan,Miller,NaN,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,NaN,dmiller@comcast.com,4
20,21,Kathy,Chase,NaN,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,NaN,kachase@hotmail.com,5
21,22,Heather,Leacock,NaN,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,NaN,hleacock@gmail.com,4
22,23,John,Gordon,NaN,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,NaN,johngordon22@yahoo.com,4
23,24,Frank,Ralston,NaN,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,NaN,fralston@gmail.com,3
24,25,Victor,Stevens,NaN,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,NaN,vstevens@yahoo.com,5
25,26,Richard,Cunningham,NaN,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,NaN,ricunningham@hotmail.com,4
26,27,Patrick,Gray,NaN,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,NaN,patrick.gray@aol.com,4
27,28,Julia,Barnett,NaN,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,NaN,jubarnett@gmail.com,5
28,29,Robert,Brown,NaN,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,NaN,robbrown@shaw.ca,3
29,30,Edward,Francis,NaN,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,NaN,edfrancis@yachoo.ca,3
30,31,Martha,Silk,NaN,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,NaN,marthasilk@gmail.com,5
31,32,Aaron,Mitchell,NaN,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,NaN,aaronmitchell@yahoo.ca,4
32,33,Ellie,Sullivan,NaN,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,NaN,ellie.sullivan@shaw.ca,3
33,34,João,Fernandes,NaN,Rua da Assunção 53,Lisbon,NaN,Portugal,NaN,+351 (213) 466-111,NaN,jfernandes@yahoo.pt,4
34,35,Madalena,Sampaio,NaN,"Rua dos Campeões Europeus de Viena, 4350",Porto,NaN,Portugal,NaN,+351 (225) 022-448,NaN,masampaio@sapo.pt,4
35,36,Hannah,Schneider,NaN,Tauentzienstraße 8,Berlin,NaN,Germany,10789,+49 030 26550280,NaN,hannah.schneider@yahoo.de,5
36,37,Fynn,Zimmermann,NaN,Berger Straße 10,Frankfurt,NaN,Germany,60316,+49 069 40598889,NaN,fzimmermann@yahoo.de,3
37,38,Niklas,Schröder,NaN,Barbarossastraße 19,Berlin,NaN,Germany,10779,+49 030 2141444,NaN,nschroder@surfeu.de,3
38,39,Camille,Bernard,NaN,"4, Rue Milton",Paris,NaN,France,75009,+33 01 49 70 65 65,NaN,camille.bernard@yahoo.fr,4
39,40,Dominique,Lefebvre,NaN,"8, Rue Hanovre",Paris,NaN,France,75002,+33 01 47 42 71 71,NaN,dominiquelefebvre@gmail.com,4
40,41,Marc,Dubois,NaN,"11, Place Bellecour",Lyon,NaN,France,69002,+33 04 78 30 30 30,NaN,marc.dubois@hotmail.com,5
41,42,Wyatt,Girard,NaN,"9, Place Louis Barthou",Bordeaux,NaN,France,33000,+33 05 56 96 96 96,NaN,wyatt.girard@yahoo.fr,3
42,43,Isabelle,Mercier,NaN,"68, Rue Jouvence",Dijon,NaN,France,21000,+33 03 80 73 66 99,NaN,isabelle_mercier@apple.fr,3
43,44,Terhi,Hämäläinen,NaN,Porthaninkatu 9,Helsinki,NaN,Finland,00530,+358 09 870 2000,NaN,terhi.hamalainen@apple.fi,3
44,45,Ladislav,Kovács,NaN,Erzsébet krt. 58.,Budapest,NaN,Hungary,H-1073,NaN,NaN,ladislav_kovacs@apple.hu,3
45,46,Hugh,O'Reilly,NaN,3 Chatham Street,Dublin,Dublin,Ireland,NaN,+353 01 6792424,NaN,hughoreilly@apple.ie,3
46,47,Lucas,Mancini,NaN,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,NaN,lucas.mancini@yahoo.it,5
47,48,Johannes,Van der Berg,NaN,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,NaN,johavanderberg@yahoo.nl,5
48,49,Stanisław,Wójcik,NaN,Ordynacka 10,Warsaw,NaN,Poland,00-358,+48 22 828 37 39,NaN,stanisław.wójcik@wp.pl,4
49,50,Enrique,Muñoz,NaN,C/ San Bernardo 85,Madrid,NaN,Spain,28015,+34 914 454 454,NaN,enrique_munoz@yahoo.es,5
50,51,Joakim,Johansson,NaN,Celsiusg. 9,Stockholm,NaN,Sweden,11230,+46 08-651 52 52,NaN,joakim.johansson@yahoo.se,5
51,52,Emma,Jones,NaN,202 Hoxton Street,London,NaN,United Kingdom,N1 5LH,+44 020 7707 0707,NaN,emma_jones@hotmail.com,3
52,53,Phil,Hughes,NaN,113 Lupus St,London,NaN,United Kingdom,SW1V 3EN,+44 020 7976 5722,NaN,phil.hughes@gmail.com,3
53,54,Steve,Murray,NaN,110 Raeburn Pl,Edinburgh,NaN,United Kingdom,EH4 1HH,+44 0131 315 3300,NaN,steve.murray@yahoo.uk,5
54,55,Mark,Taylor,NaN,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,NaN,mark.taylor@yahoo.au,4
55,56,Diego,Gutiérrez,NaN,307 Macacha Güemes,Buenos Aires,NaN,Argentina,1106,+54 (0)11 4311 4333,NaN,diego.gutierrez@yahoo.ar,4
56,57,Luis,Rojas,NaN,"Calle Lira, 198",Santiago,NaN,Chile,NaN,+56 (0)2 635 4444,NaN,luisrojas@yahoo.cl,5
57,58,Manoj,Pareek,NaN,"12,Community Centre",Delhi,NaN,India,110017,+91 0124 39883988,NaN,manoj.pareek@rediff.com,3
58,59,Puja,Srivastava,NaN,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,+91 080 22289999,NaN,puja_srivastava@yahoo.in,3

In [21]:
q = """select first_name ||" "|| last_name Customer_name, Phone Contact from customer
"""
sql_query(q)

            Customer_name              Contact
0          Luís Gonçalves   +55 (12) 3923-5555
1           Leonie Köhler     +49 0711 2842222
2       François Tremblay    +1 (514) 721-4711
3            Bjørn Hansen      +47 22 44 22 22
4   František Wichterlová     +420 2 4172 5555
5             Helena Holý     +420 2 4177 0449
6           Astrid Gruber       +43 01 5134505
7            Daan Peeters     +32 02 219 03 03
8            Kara Nielsen       +453 3331 9991
9         Eduardo Martins   +55 (11) 3033-5446
10        Alexandre Rocha   +55 (11) 3055-3278
11        Roberto Almeida   +55 (21) 2271-7000
12         Fernanda Ramos   +55 (61) 3363-5547
13           Mark Philips    +1 (780) 434-4554
14      Jennifer Peterson    +1 (604) 688-2255
15           Frank Harris    +1 (650) 253-0000
16             Jack Smith    +1 (425) 882-8080
17        Michelle Brooks    +1 (212) 221-3546
18              Tim Goyer    +1 (408) 996-1010
19             Dan Miller    +1 (650) 644-3358
20            Kathy Chase    +1 (775) 223-7665
21        Heather Leacock    +1 (407) 999-7788
22            John Gordon    +1 (617) 522-1333
23          Frank Ralston    +1 (312) 332-3232
24         Victor Stevens    +1 (608) 257-0597
25     Richard Cunningham    +1 (817) 924-7272
26           Patrick Gray    +1 (520) 622-4200
27          Julia Barnett    +1 (801) 531-7272
28           Robert Brown    +1 (416) 363-8888
29         Edward Francis    +1 (613) 234-3322
30            Martha Silk    +1 (902) 450-0450
31         Aaron Mitchell    +1 (204) 452-6452
32         Ellie Sullivan    +1 (867) 920-2233
33         João Fernandes   +351 (213) 466-111
34       Madalena Sampaio   +351 (225) 022-448
35       Hannah Schneider     +49 030 26550280
36        Fynn Zimmermann     +49 069 40598889
37        Niklas Schröder      +49 030 2141444
38        Camille Bernard   +33 01 49 70 65 65
39     Dominique Lefebvre   +33 01 47 42 71 71
40            Marc Dubois   +33 04 78 30 30 30
41           Wyatt Girard   +33 05 56 96 96 96
42       Isabelle Mercier   +33 03 80 73 66 99
43       Terhi Hämäläinen     +358 09 870 2000
44        Ladislav Kovács                  NaN
45          Hugh O'Reilly      +353 01 6792424
46          Lucas Mancini      +39 06 39733434
47  Johannes Van der Berg      +31 020 6223130
48       Stanisław Wójcik     +48 22 828 37 39
49          Enrique Muñoz      +34 914 454 454
50       Joakim Johansson     +46 08-651 52 52
51             Emma Jones    +44 020 7707 0707
52            Phil Hughes    +44 020 7976 5722
53           Steve Murray    +44 0131 315 3300
54            Mark Taylor   +61 (02) 9332 3633
55        Diego Gutiérrez  +54 (0)11 4311 4333
56             Luis Rojas    +56 (0)2 635 4444
57           Manoj Pareek    +91 0124 39883988
58        Puja Srivastava     +91 080 22289999

In [22]:
q = """select first_name ||" "|| last_name Customer_name, Phone Contact from customer
        where first_name Like "%jen%"
"""
sql_query(q)

       Customer_name            Contact
0  Jennifer Peterson  +1 (604) 688-2255

## '_' The first word could be anything and then would be matches the pattern

In [23]:
q = """select first_name ||" "|| last_name Customer_name, Phone Contact from customer
        where first_name Like "_en%"
"""
sql_query(q)

       Customer_name            Contact
0  Jennifer Peterson  +1 (604) 688-2255

In [24]:
q = """select first_name ||" "|| last_name Customer_name, Phone Contact from customer
        where first_name Like "_an%"
"""
sql_query(q)

      Customer_name            Contact
0        Dan Miller  +1 (650) 644-3358
1  Hannah Schneider   +49 030 26550280
2      Manoj Pareek  +91 0124 39883988

In [25]:
 # if use '%' in starting so given pattern returns any word in "an" whatever in starting
 # and ending or center code return all these type of results 

q = """select first_name ||" "|| last_name Customer_name, Phone Contact from customer
        where first_name Like "%an%"
"""

sql_query(q)

            Customer_name             Contact
0       François Tremblay   +1 (514) 721-4711
1   František Wichterlová    +420 2 4172 5555
2            Daan Peeters    +32 02 219 03 03
3         Alexandre Rocha  +55 (11) 3055-3278
4          Fernanda Ramos  +55 (61) 3363-5547
5            Frank Harris   +1 (650) 253-0000
6              Dan Miller   +1 (650) 644-3358
7           Frank Ralston   +1 (312) 332-3232
8        Hannah Schneider    +49 030 26550280
9   Johannes Van der Berg     +31 020 6223130
10       Stanisław Wójcik    +48 22 828 37 39
11           Manoj Pareek   +91 0124 39883988

## Top five Customer_name, No_of_invoices, Total_spent

In [26]:
q = """select c.first_name ||" "|| c.last_name Customer_name,
        count(inv.invoice_id) No_of_Invoices,
        sum(inv.total) Total_spent
        from customer c
        inner join invoice inv
        on
        c.customer_id = inv.customer_id
        
        group by c.customer_id
        order by 3 DESC limit 5

"""
sql_query(q)

           Customer_name  No_of_Invoices  Total_spent
0  František Wichterlová              18       144.54
1            Helena Holý              12       128.70
2          Hugh O'Reilly              13       114.84
3           Manoj Pareek              13       111.87
4         Luís Gonçalves              13       108.90

## Add new col customer_category

In [27]:

q = '''SELECT first_name || ' ' || last_name Customer_Name, 
        count(inv.invoice_id) No_Of_Invoices,
        sum(total) Total_Spent,
        Case
            when sum(inv.total) < 40 then "Small Spender"
            when sum(inv.total) > 100 then "Big Spender"
            Else "Regular"
        End as Customer_category
        from customer c
        inner join invoice inv
        on 
        c.customer_id = inv.customer_id
        group by c.customer_id
        
        
'''
sql_query(q)

            Customer_Name  No_Of_Invoices  Total_Spent Customer_category
0          Luís Gonçalves              13       108.90       Big Spender
1           Leonie Köhler              11        82.17           Regular
2       François Tremblay               9        99.99           Regular
3            Bjørn Hansen               9        72.27           Regular
4   František Wichterlová              18       144.54       Big Spender
5             Helena Holý              12       128.70       Big Spender
6           Astrid Gruber               9        69.30           Regular
7            Daan Peeters               7        60.39           Regular
8            Kara Nielsen              10        37.62     Small Spender
9         Eduardo Martins              12        60.39           Regular
10        Alexandre Rocha              10        69.30           Regular
11        Roberto Almeida              11        82.17           Regular
12         Fernanda Ramos              15       106.92       Big Spender
13           Mark Philips              10        29.70     Small Spender
14      Jennifer Peterson               9        66.33           Regular
15           Frank Harris               8        74.25           Regular
16             Jack Smith              12        98.01           Regular
17        Michelle Brooks               8        79.20           Regular
18              Tim Goyer               9        54.45           Regular
19             Dan Miller              12        95.04           Regular
20            Kathy Chase              11        91.08           Regular
21        Heather Leacock              12        92.07           Regular
22            John Gordon              10        66.33           Regular
23          Frank Ralston               8        71.28           Regular
24         Victor Stevens              10        76.23           Regular
25     Richard Cunningham              12        86.13           Regular
26           Patrick Gray               9        84.15           Regular
27          Julia Barnett              10        72.27           Regular
28           Robert Brown               4        40.59           Regular
29         Edward Francis              13        91.08           Regular
30            Martha Silk              11        62.37           Regular
31         Aaron Mitchell               8        70.29           Regular
32         Ellie Sullivan              12        75.24           Regular
33         João Fernandes              13       102.96       Big Spender
34       Madalena Sampaio              16        82.17           Regular
35       Hannah Schneider              11        85.14           Regular
36        Fynn Zimmermann              10        94.05           Regular
37        Niklas Schröder               9        73.26           Regular
38        Camille Bernard               9        79.20           Regular
39     Dominique Lefebvre               9        72.27           Regular
40            Marc Dubois               9        64.35           Regular
41           Wyatt Girard              11        99.99           Regular
42       Isabelle Mercier              12        73.26           Regular
43       Terhi Hämäläinen              11        79.20           Regular
44        Ladislav Kovács              10        78.21           Regular
45          Hugh O'Reilly              13       114.84       Big Spender
46          Lucas Mancini               9        50.49           Regular
47  Johannes Van der Berg              10        65.34           Regular
48       Stanisław Wójcik              10        76.23           Regular
49          Enrique Muñoz              11        98.01           Regular
50       Joakim Johansson              10        75.24           Regular
51             Emma Jones               8        68.31           Regular
52            Phil Hughes              11        98.01           Regular
53           Steve Murray               9        79.20           Regular
54            Mark Taylor              10        81.18           Regular
55        Diego Gutiérrez               5        39.60     Small Spender
56             Luis Rojas              13        97.02           Regular
57           Manoj Pareek              13       111.87       Big Spender
58        Puja Srivastava               8        71.28           Regular

In [28]:
# value_count 
q = '''SELECT first_name || ' ' || last_name Customer_Name, 
        count(inv.invoice_id) No_Of_Invoices,
        sum(total) Total_Spent,
        Case
            when sum(inv.total) < 40 then "Small Spender"
            when sum(inv.total) > 100 then "Big Spender"
            Else "Regular"
        End as Customer_category
        from customer c
        inner join invoice inv
        on 
        c.customer_id = inv.customer_id
        group by c.customer_id
        order by 1
        
'''
sql_query(q)["Customer_category"].value_counts()

Customer_category
Regular          49
Big Spender       7
Small Spender     3
Name: count, dtype: int64

## Customer all col , total invoice where total_spent > 90

In [29]:
q = """select c.*, sum(inv.total) Total_Spent
        from customer c
        left join invoice inv
        on
        c.customer_id = inv.customer_id
        group by c.customer_id
"""
sql_query(q)

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id,Total_Spent
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3,108.90
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5,82.17
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3,99.99
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,0171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4,72.27
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4,144.54
5,6,Helena,Holý,NaN,Rilská 3174/6,Prague,NaN,Czech Republic,14300,+420 2 4177 0449,NaN,hholy@gmail.com,5,128.70
6,7,Astrid,Gruber,NaN,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,NaN,Austria,1010,+43 01 5134505,NaN,astrid.gruber@apple.at,5,69.30
7,8,Daan,Peeters,NaN,Grétrystraat 63,Brussels,NaN,Belgium,1000,+32 02 219 03 03,NaN,daan_peeters@apple.be,4,60.39
8,9,Kara,Nielsen,NaN,Sønder Boulevard 51,Copenhagen,NaN,Denmark,1720,+453 3331 9991,NaN,kara.nielsen@jubii.dk,4,37.62
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4,60.39
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5,69.30
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3,82.17
12,13,Fernanda,Ramos,NaN,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4,106.92
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5,29.70
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3,66.33
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4,74.25
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5,98.01
17,18,Michelle,Brooks,NaN,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3,79.20
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3,54.45
19,20,Dan,Miller,NaN,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,NaN,dmiller@comcast.com,4,95.04
20,21,Kathy,Chase,NaN,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,NaN,kachase@hotmail.com,5,91.08
21,22,Heather,Leacock,NaN,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,NaN,hleacock@gmail.com,4,92.07
22,23,John,Gordon,NaN,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,NaN,johngordon22@yahoo.com,4,66.33
23,24,Frank,Ralston,NaN,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,NaN,fralston@gmail.com,3,71.28
24,25,Victor,Stevens,NaN,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,NaN,vstevens@yahoo.com,5,76.23
25,26,Richard,Cunningham,NaN,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,NaN,ricunningham@hotmail.com,4,86.13
26,27,Patrick,Gray,NaN,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,NaN,patrick.gray@aol.com,4,84.15
27,28,Julia,Barnett,NaN,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,NaN,jubarnett@gmail.com,5,72.27
28,29,Robert,Brown,NaN,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,NaN,robbrown@shaw.ca,3,40.59
29,30,Edward,Francis,NaN,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,NaN,edfrancis@yachoo.ca,3,91.08
30,31,Martha,Silk,NaN,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,NaN,marthasilk@gmail.com,5,62.37
31,32,Aaron,Mitchell,NaN,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,NaN,aaronmitchell@yahoo.ca,4,70.29
32,33,Ellie,Sullivan,NaN,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,NaN,ellie.sullivan@shaw.ca,3,75.24
33,34,João,Fernandes,NaN,Rua da Assunção 53,Lisbon,NaN,Portugal,NaN,+351 (213) 466-111,NaN,jfernandes@yahoo.pt,4,102.96
34,35,Madalena,Sampaio,NaN,"Rua dos Campeões Europeus de Viena, 4350",Porto,NaN,Portugal,NaN,+351 (225) 022-448,NaN,masampaio@sapo.pt,4,82.17
35,36,Hannah,Schneider,NaN,Tauentzienstraße 8,Berlin,NaN,Germany,10789,+49 030 26550280,NaN,hannah.schneider@yahoo.de,5,85.14
36,37,Fynn,Zimmermann,NaN,Berger Straße 10,Frankfurt,NaN,Germany,60316,+49 069 40598889,NaN,fzimmermann@yahoo.de,3,94.05
37,38,Niklas,Schröder,NaN,Barbarossastraße 19,Berlin,NaN,Germany,10779,+49 030 2141444,NaN,nschroder@surfeu.de,3,73.26
38,39,Camille,Bernard,NaN,"4, Rue Milton",Paris,NaN,France,75009,+33 01 49 70 65 65,NaN,camille.bernard@yahoo.fr,4,79.20
39,40,Dominique,Lefebvre,NaN,"8, Rue Hanovre",Paris,NaN,France,75002,+33 01 47 42 71 71,NaN,dominiquelefebvre@gmail.com,4,72.27
40,41,Marc,Dubois,NaN,"11, Place Bellecour",Lyon,NaN,France,69002,+33 04 78 30 30 30,NaN,marc.dubois@hotmail.com,5,64.35
41,42,Wyatt,Girard,NaN,"9, Place Louis Barthou",Bordeaux,NaN,France,33000,+33 05 56 96 96 96,NaN,wyatt.girard@yahoo.fr,3,99.99
42,43,Isabelle,Mercier,NaN,"68, Rue Jouvence",Dijon,NaN,France,21000,+33 03 80 73 66 99,NaN,isabelle_mercier@apple.fr,3,73.26
43,44,Terhi,Hämäläinen,NaN,Porthaninkatu 9,Helsinki,NaN,Finland,00530,+358 09 870 2000,NaN,terhi.hamalainen@apple.fi,3,79.20
44,45,Ladislav,Kovács,NaN,Erzsébet krt. 58.,Budapest,NaN,Hungary,H-1073,NaN,NaN,ladislav_kovacs@apple.hu,3,78.21
45,46,Hugh,O'Reilly,NaN,3 Chatham Street,Dublin,Dublin,Ireland,NaN,+353 01 6792424,NaN,hughoreilly@apple.ie,3,114.84
46,47,Lucas,Mancini,NaN,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,NaN,lucas.mancini@yahoo.it,5,50.49
47,48,Johannes,Van der Berg,NaN,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,NaN,johavanderberg@yahoo.nl,5,65.34
48,49,Stanisław,Wójcik,NaN,Ordynacka 10,Warsaw,NaN,Poland,00-358,+48 22 828 37 39,NaN,stanisław.wójcik@wp.pl,4,76.23
49,50,Enrique,Muñoz,NaN,C/ San Bernardo 85,Madrid,NaN,Spain,28015,+34 914 454 454,NaN,enrique_munoz@yahoo.es,5,98.01
50,51,Joakim,Johansson,NaN,Celsiusg. 9,Stockholm,NaN,Sweden,11230,+46 08-651 52 52,NaN,joakim.johansson@yahoo.se,5,75.24
51,52,Emma,Jones,NaN,202 Hoxton Street,London,NaN,United Kingdom,N1 5LH,+44 020 7707 0707,NaN,emma_jones@hotmail.com,3,68.31
52,53,Phil,Hughes,NaN,113 Lupus St,London,NaN,United Kingdom,SW1V 3EN,+44 020 7976 5722,NaN,phil.hughes@gmail.com,3,98.01
53,54,Steve,Murray,NaN,110 Raeburn Pl,Edinburgh,NaN,United Kingdom,EH4 1HH,+44 0131 315 3300,NaN,steve.murray@yahoo.uk,5,79.20
54,55,Mark,Taylor,NaN,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,NaN,mark.taylor@yahoo.au,4,81.18
55,56,Diego,Gutiérrez,NaN,307 Macacha Güemes,Buenos Aires,NaN,Argentina,1106,+54 (0)11 4311 4333,NaN,diego.gutierrez@yahoo.ar,4,39.60
56,57,Luis,Rojas,NaN,"Calle Lira, 198",Santiago,NaN,Chile,NaN,+56 (0)2 635 4444,NaN,luisrojas@yahoo.cl,5,97.02
57,58,Manoj,Pareek,NaN,"12,Community Centre",Delhi,NaN,India,110017,+91 0124 39883988,NaN,manoj.pareek@rediff.com,3,111.87
58,59,Puja,Srivastava,NaN,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,+91 080 22289999,NaN,puja_srivastava@yahoo.in,3,71.28

In [30]:
q = """select c.*, sum(inv.total) Total_Spent
        from customer c
        left join invoice inv
        on
        c.customer_id = inv.customer_id
        group by c.customer_id
        having Total_Spent > 90

"""
sql_query(q)

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id,Total_Spent
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3,108.90
1,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3,99.99
2,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4,144.54
3,6,Helena,Holý,NaN,Rilská 3174/6,Prague,NaN,Czech Republic,14300,+420 2 4177 0449,NaN,hholy@gmail.com,5,128.70
4,13,Fernanda,Ramos,NaN,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4,106.92
5,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5,98.01
6,20,Dan,Miller,NaN,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,NaN,dmiller@comcast.com,4,95.04
7,21,Kathy,Chase,NaN,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,NaN,kachase@hotmail.com,5,91.08
8,22,Heather,Leacock,NaN,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,NaN,hleacock@gmail.com,4,92.07
9,30,Edward,Francis,NaN,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,NaN,edfrancis@yachoo.ca,3,91.08
10,34,João,Fernandes,NaN,Rua da Assunção 53,Lisbon,NaN,Portugal,NaN,+351 (213) 466-111,NaN,jfernandes@yahoo.pt,4,102.96
11,37,Fynn,Zimmermann,NaN,Berger Straße 10,Frankfurt,NaN,Germany,60316,+49 069 40598889,NaN,fzimmermann@yahoo.de,3,94.05
12,42,Wyatt,Girard,NaN,"9, Place Louis Barthou",Bordeaux,NaN,France,33000,+33 05 56 96 96 96,NaN,wyatt.girard@yahoo.fr,3,99.99
13,46,Hugh,O'Reilly,NaN,3 Chatham Street,Dublin,Dublin,Ireland,NaN,+353 01 6792424,NaN,hughoreilly@apple.ie,3,114.84
14,50,Enrique,Muñoz,NaN,C/ San Bernardo 85,Madrid,NaN,Spain,28015,+34 914 454 454,NaN,enrique_munoz@yahoo.es,5,98.01
15,53,Phil,Hughes,NaN,113 Lupus St,London,NaN,United Kingdom,SW1V 3EN,+44 020 7976 5722,NaN,phil.hughes@gmail.com,3,98.01
16,57,Luis,Rojas,NaN,"Calle Lira, 198",Santiago,NaN,Chile,NaN,+56 (0)2 635 4444,NaN,luisrojas@yahoo.cl,5,97.02
17,58,Manoj,Pareek,NaN,"12,Community Centre",Delhi,NaN,India,110017,+91 0124 39883988,NaN,manoj.pareek@rediff.com,3,111.87

In [31]:
# customer all col , Top 3 total invoice
q = """select c.*, sum(inv.total) Total_Spent
        from customer c
        left join invoice inv
        on
        c.customer_id = inv.customer_id
        group by c.customer_id
        having Total_Spent > 90
        order by Total_Spent DESC limit 3
        

"""
sql_query(q)

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id,Total_Spent
0,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4,144.54
1,6,Helena,Holý,NaN,Rilská 3174/6,Prague,NaN,Czech Republic,14300,+420 2 4177 0449,NaN,hholy@gmail.com,5,128.70
2,46,Hugh,O'Reilly,NaN,3 Chatham Street,Dublin,Dublin,Ireland,NaN,+353 01 6792424,NaN,hughoreilly@apple.ie,3,114.84

In [32]:
q =  '''select * from sqlite_master where type = 'table'

'''
sql_query(q)

,type,name,tbl_name,rootpage,sql
0,table,album,album,2,CREATE TABLE [album]\n(\n [album_id] INTEGE...
1,table,artist,artist,3,CREATE TABLE [artist]\n(\n [artist_id] INTE...
2,table,customer,customer,4,CREATE TABLE [customer]\n(\n [customer_id] ...
3,table,employee,employee,5,CREATE TABLE [employee]\n(\n [employee_id] ...
4,table,genre,genre,6,CREATE TABLE [genre]\n(\n [genre_id] INTEGE...
5,table,invoice,invoice,7,CREATE TABLE [invoice]\n(\n [invoice_id] IN...
6,table,invoice_line,invoice_line,8,CREATE TABLE [invoice_line]\n(\n [invoice_l...
7,table,media_type,media_type,9,CREATE TABLE [media_type]\n(\n [media_type_...
8,table,playlist,playlist,10,CREATE TABLE [playlist]\n(\n [playlist_id] ...
9,table,playlist_track,playlist_track,11,CREATE TABLE [playlist_track]\n(\n [playlis...
10,table,track,track,13,CREATE TABLE [track]\n(\n [track_id] INTEGE...
11,table,wishlist_track,wishlist_track,261,CREATE TABLE wishlist_track(\nwishlist_id Inte...
12,table,wishlist,wishlist,260,"CREATE TABLE ""wishlist"" (\n\t""whishlist_id""\tI..."

In [33]:
# Create table

q = """create table Top_3_CUSTOMER as 
        select c.*, sum(inv.total) Total_Spent
        from customer c
        left join invoice inv
        on
        c.customer_id = inv.customer_id
        group by c.customer_id
        having Total_Spent > 90
        order by Total_Spent DESC limit 3
        

"""
conn.execute(q)

In [34]:
sql_query("select * from sqlite_master where type = 'table'")

,type,name,tbl_name,rootpage,sql
0,table,album,album,2,CREATE TABLE [album]\n(\n [album_id] INTEGE...
1,table,artist,artist,3,CREATE TABLE [artist]\n(\n [artist_id] INTE...
2,table,customer,customer,4,CREATE TABLE [customer]\n(\n [customer_id] ...
3,table,employee,employee,5,CREATE TABLE [employee]\n(\n [employee_id] ...
4,table,genre,genre,6,CREATE TABLE [genre]\n(\n [genre_id] INTEGE...
5,table,invoice,invoice,7,CREATE TABLE [invoice]\n(\n [invoice_id] IN...
6,table,invoice_line,invoice_line,8,CREATE TABLE [invoice_line]\n(\n [invoice_l...
7,table,media_type,media_type,9,CREATE TABLE [media_type]\n(\n [media_type_...
8,table,playlist,playlist,10,CREATE TABLE [playlist]\n(\n [playlist_id] ...
9,table,playlist_track,playlist_track,11,CREATE TABLE [playlist_track]\n(\n [playlis...
10,table,track,track,13,CREATE TABLE [track]\n(\n [track_id] INTEGE...
11,table,wishlist_track,wishlist_track,261,CREATE TABLE wishlist_track(\nwishlist_id Inte...
12,table,wishlist,wishlist,260,"CREATE TABLE ""wishlist"" (\n\t""whishlist_id""\tI..."
13,table,Top_3_CUSTOMER,Top_3_CUSTOMER,266,CREATE TABLE Top_3_CUSTOMER(\n customer_id IN...

In [35]:
q = '''select * from Top_3_CUSTOMER'''
sql_query(q)

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id,Total_Spent
0,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4,144.54
1,6,Helena,Holý,NaN,Rilská 3174/6,Prague,NaN,Czech Republic,14300,+420 2 4177 0449,NaN,hholy@gmail.com,5,128.70
2,46,Hugh,O'Reilly,NaN,3 Chatham Street,Dublin,Dublin,Ireland,NaN,+353 01 6792424,NaN,hughoreilly@apple.ie,3,114.84

In [36]:
# track_id, total_sale

q = """SELECT t.track_id, sum(il.quantity) Total_Sale FROM track t
        left JOIN invoice_line il
        ON
        t.track_id = il.track_id
        GROUP BY 1
        """

sql_query(q)

      track_id  Total_Sale
0            1         8.0
1            2         3.0
2            3         1.0
3            4         4.0
4            5         1.0
...        ...         ...
3498      3499         NaN
3499      3500         2.0
3500      3501         NaN
3501      3502         NaN
3502      3503         NaN

[3503 rows x 2 columns]

In [37]:
# After three letter 'en' would be match because given ___ so that's why

q = """SELECT first_name || " " || last_name Customer_Name, Phone FROM customer
        WHERE first_name LIKE '___en%'
        group by 1"""

sql_query(q)

  Customer_Name             phone
0   Helena Holý  +420 2 4177 0449

In [38]:
# Another Example
q = """SELECT first_name || " " || last_name Customer_Name, Phone FROM customer
        WHERE first_name LIKE '___an%'
        group by 1"""

sql_query(q)

           Customer_Name            phone
0  Johannes Van der Berg  +31 020 6223130

In [39]:
q = """SELECT first_name || " " || last_name Customer_Name, Phone FROM customer
        WHERE first_name LIKE '_e_ni_er' """

sql_query(q)

       Customer_Name              phone
0  Jennifer Peterson  +1 (604) 688-2255

In [40]:
q = "select * from sqlite_master"
sql_query(q)

,type,name,tbl_name,rootpage,sql
0,table,album,album,2,CREATE TABLE [album]\n(\n [album_id] INTEGE...
1,table,artist,artist,3,CREATE TABLE [artist]\n(\n [artist_id] INTE...
2,table,customer,customer,4,CREATE TABLE [customer]\n(\n [customer_id] ...
3,table,employee,employee,5,CREATE TABLE [employee]\n(\n [employee_id] ...
4,table,genre,genre,6,CREATE TABLE [genre]\n(\n [genre_id] INTEGE...
5,table,invoice,invoice,7,CREATE TABLE [invoice]\n(\n [invoice_id] IN...
6,table,invoice_line,invoice_line,8,CREATE TABLE [invoice_line]\n(\n [invoice_l...
7,table,media_type,media_type,9,CREATE TABLE [media_type]\n(\n [media_type_...
8,table,playlist,playlist,10,CREATE TABLE [playlist]\n(\n [playlist_id] ...
9,table,playlist_track,playlist_track,11,CREATE TABLE [playlist_track]\n(\n [playlis...
10,index,sqlite_autoindex_playlist_track_1,playlist_track,12,NaN
11,table,track,track,13,CREATE TABLE [track]\n(\n [track_id] INTEGE...
12,index,ifk_albumartist_id,album,16,CREATE INDEX [ifk_albumartist_id] ON [album] (...
13,index,ifk_customersupport_rep_id,customer,17,CREATE INDEX [ifk_customersupport_rep_id] ON [...
14,index,ifk_employeereports_to,employee,18,CREATE INDEX [ifk_employeereports_to] ON [empl...
15,index,ifk_invoicecustomer_id,invoice,19,CREATE INDEX [ifk_invoicecustomer_id] ON [invo...
16,index,ifk_invoice_lineinvoice_id,invoice_line,20,CREATE INDEX [ifk_invoice_lineinvoice_id] ON [...
17,index,ifk_invoice_linetrack_id,invoice_line,21,CREATE INDEX [ifk_invoice_linetrack_id] ON [in...
18,index,ifk_playlist_tracktrack_id,playlist_track,22,CREATE INDEX [ifk_playlist_tracktrack_id] ON [...
19,index,ifk_trackalbum_id,track,23,CREATE INDEX [ifk_trackalbum_id] ON [track] ([...
20,index,ifk_trackgenre_id,track,24,CREATE INDEX [ifk_trackgenre_id] ON [track] ([...
21,index,ifk_trackmedia_type_id,track,25,CREATE INDEX [ifk_trackmedia_type_id] ON [trac...
22,table,wishlist_track,wishlist_track,261,CREATE TABLE wishlist_track(\nwishlist_id Inte...
23,index,sqlite_autoindex_wishlist_track_1,wishlist_track,262,NaN
24,table,wishlist,wishlist,260,"CREATE TABLE ""wishlist"" (\n\t""whishlist_id""\tI..."
25,view,CUSTOMER_ABV2_90,CUSTOMER_ABV2_90,0,CREATE VIEW CUSTOMER_ABV2_90 as \n sele...
26,view,customer_get_90_dollars,customer_get_90_dollars,0,CREATE VIEW customer_get_90_dollars as\n Sel...
27,view,customer_usa,customer_usa,0,CREATE VIEW customer_usa as\n sele...
28,view,customer_gt_90_dollars,customer_gt_90_dollars,0,CREATE VIEW customer_gt_90_dollars as\n Sele...
29,view,city_redmond,city_redmond,0,CREATE VIEW city_redmond as\n sele...
30,view,CUSTOMER_ABV3_80,CUSTOMER_ABV3_80,0,CREATE VIEW CUSTOMER_ABV3_80 as \n sele...
31,table,Top_3_CUSTOMER,Top_3_CUSTOMER,266,CREATE TABLE Top_3_CUSTOMER(\n customer_id IN...

In [41]:
# Drop table Top_3_CUSTOMER
conn.execute("Drop table Top_3_CUSTOMER")

In [42]:
q = "select * from sqlite_master where type='table'"
sql_query(q)

,type,name,tbl_name,rootpage,sql
0,table,album,album,2,CREATE TABLE [album]\n(\n [album_id] INTEGE...
1,table,artist,artist,3,CREATE TABLE [artist]\n(\n [artist_id] INTE...
2,table,customer,customer,4,CREATE TABLE [customer]\n(\n [customer_id] ...
3,table,employee,employee,5,CREATE TABLE [employee]\n(\n [employee_id] ...
4,table,genre,genre,6,CREATE TABLE [genre]\n(\n [genre_id] INTEGE...
5,table,invoice,invoice,7,CREATE TABLE [invoice]\n(\n [invoice_id] IN...
6,table,invoice_line,invoice_line,8,CREATE TABLE [invoice_line]\n(\n [invoice_l...
7,table,media_type,media_type,9,CREATE TABLE [media_type]\n(\n [media_type_...
8,table,playlist,playlist,10,CREATE TABLE [playlist]\n(\n [playlist_id] ...
9,table,playlist_track,playlist_track,11,CREATE TABLE [playlist_track]\n(\n [playlis...
10,table,track,track,13,CREATE TABLE [track]\n(\n [track_id] INTEGE...
11,table,wishlist_track,wishlist_track,261,CREATE TABLE wishlist_track(\nwishlist_id Inte...
12,table,wishlist,wishlist,260,"CREATE TABLE ""wishlist"" (\n\t""whishlist_id""\tI..."

# customer from each country that has spent the most money at our store Best customer_id, Customer_name, Country, Top_Buyer

In [44]:
#  customer from each country that has spent the most money at our store
# Best customer_id, Customer_name, Country, Top_Buyer

q = """with best_customer_id as
       (select c.customer_id, c.first_name ||" "|| c.last_name full_name, c.country,
       sum(i.total) Total_purchased
       from customer c
       inner join invoice i 
       on
       c.customer_id = i.customer_id
       group by 1)
       
       
       select customer_id, country, full_name, max(Total_purchased) Top_buyer
       from best_customer_id
       group by 2


    """

In [45]:
sql_query(q)

    customer_id         country              full_name  Top_buyer
0            56       Argentina        Diego Gutiérrez      39.60
1            55       Australia            Mark Taylor      81.18
2             7         Austria          Astrid Gruber      69.30
3             8         Belgium           Daan Peeters      60.39
4             1          Brazil         Luís Gonçalves     108.90
5             3          Canada      François Tremblay      99.99
6            57           Chile             Luis Rojas      97.02
7             5  Czech Republic  František Wichterlová     144.54
8             9         Denmark           Kara Nielsen      37.62
9            44         Finland       Terhi Hämäläinen      79.20
10           42          France           Wyatt Girard      99.99
11           37         Germany        Fynn Zimmermann      94.05
12           45         Hungary        Ladislav Kovács      78.21
13           58           India           Manoj Pareek     111.87
14           46         Ireland          Hugh O'Reilly     114.84
15           47           Italy          Lucas Mancini      50.49
16           48     Netherlands  Johannes Van der Berg      65.34
17            4          Norway           Bjørn Hansen      72.27
18           49          Poland       Stanisław Wójcik      76.23
19           34        Portugal         João Fernandes     102.96
20           50           Spain          Enrique Muñoz      98.01
21           51          Sweden       Joakim Johansson      75.24
22           17             USA             Jack Smith      98.01
23           53  United Kingdom            Phil Hughes      98.01