In [2]:
import pandas as pd
import sqlite3 as sql

In [3]:
conn = sql.connect('factbook.db')
conn

In [4]:
def sql_query(q):
    return pd.read_sql_query(q,conn)

In [6]:
q = 'select * from sqlite_master'

In [7]:
q = """select * from facts
   where name =='Pakistan'

"""
sql_query(q)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,132,pk,Pakistan,796095,770875,25220,199085847,1.46,22.58,6.49,1.54

In [11]:
q = """select * from cities
    where facts_id == 132

"""
sql_query(q)

    id        name  population  capital facts_id
0  273     Karachi    13876000        0      132
1  274      Lahore     7566000        0      132
2  275  Faisalabad     3038000        0      132
3  276  Rawalpindi     2164000        0      132
4  277      Multan     1775000        0      132
5  278   Islamabad      919000        1      132

In [12]:
q = """select * from facts f
       inner join cities c
       on
       f.id == c.facts_id
    

"""
sql_query(q)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate,id,name,population,capital,facts_id
0,216,aa,Aruba,180.0,180.0,0.0,112162,1.33,12.56,8.18,8.92,1,Oranjestad,37000,1,216
1,6,ac,Antigua and Barbuda,442.0,442.0,0.0,92436,1.24,15.85,5.69,2.21,2,Saint John'S,27000,1,6
2,184,ae,United Arab Emirates,83600.0,83600.0,0.0,5779760,2.58,15.43,1.97,12.36,3,Abu Dhabi,942000,1,184
3,184,ae,United Arab Emirates,83600.0,83600.0,0.0,5779760,2.58,15.43,1.97,12.36,4,Dubai,1978000,0,184
4,184,ae,United Arab Emirates,83600.0,83600.0,0.0,5779760,2.58,15.43,1.97,12.36,5,Sharjah,983000,0,184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,167,wz,Swaziland,17364.0,17204.0,160.0,1435613,1.11,24.67,13.56,0.00,393,Mbabane,66000,1,167
393,193,ym,Yemen,527968.0,527968.0,0.0,26737317,2.47,29.98,6.28,1.00,394,Sanaa,2419000,1,193
394,193,ym,Yemen,527968.0,527968.0,0.0,26737317,2.47,29.98,6.28,1.00,395,Aden,784000,0,193
395,194,za,Zambia,752618.0,743398.0,9220.0,15066266,2.88,42.13,12.67,0.68,396,Lusaka,1802000,1,194
396,195,zi,Zimbabwe,390757.0,386847.0,3910.0,14229541,2.21,32.26,10.13,0.00,397,Harare,1542000,1,195

In [14]:
q = """select f.name Country_name, c.name City from facts f
       inner join cities c
       on
       f.id == c.facts_id
       where f.name == "Pakistan" 
    

"""
sql_query(q)

  Country_name        City
0     Pakistan     Karachi
1     Pakistan      Lahore
2     Pakistan  Faisalabad
3     Pakistan  Rawalpindi
4     Pakistan      Multan
5     Pakistan   Islamabad

In [20]:
q = """select
           f.name AS Country_name,
           c.name AS City
       from facts f
       left join cities c
       On
       f.id = c.facts_id
       where c.id is null
"""

sql_query(q)

                                     Country_name  City
0                                          Kosovo  None
1                                          Monaco  None
2                                           Nauru  None
3                                      San Marino  None
4                                       Singapore  None
5                         Holy See (Vatican City)  None
6                                          Taiwan  None
7                                  European Union  None
8                     Ashmore and Cartier Islands  None
9                                Christmas Island  None
10                        Cocos (Keeling) Islands  None
11                              Coral Sea Islands  None
12              Heard Island and McDonald Islands  None
13                                 Norfolk Island  None
14                                      Hong Kong  None
15                                          Macau  None
16                              Clipperton Island  None
17            French Southern and Antarctic Lands  None
18                               Saint Barthelemy  None
19                                   Saint Martin  None
20                                        Curacao  None
21                                   Sint Maarten  None
22                                   Cook Islands  None
23                                           Niue  None
24                                        Tokelau  None
25                                  Bouvet Island  None
26                                      Jan Mayen  None
27                                       Svalbard  None
28                                       Akrotiri  None
29                 British Indian Ocean Territory  None
30                                       Dhekelia  None
31                                      Gibraltar  None
32                                       Guernsey  None
33                                         Jersey  None
34                                     Montserrat  None
35                               Pitcairn Islands  None
36       South Georgia and South Sandwich Islands  None
37                                 Navassa Island  None
38                                    Wake Island  None
39  United States Pacific Island Wildlife Refuges  None
40                                     Antarctica  None
41                                     Gaza Strip  None
42                                Paracel Islands  None
43                                Spratly Islands  None
44                                      West Bank  None
45                                   Arctic Ocean  None
46                                 Atlantic Ocean  None
47                                   Indian Ocean  None
48                                  Pacific Ocean  None
49                                 Southern Ocean  None
50                                          World  None

In [22]:
q = """select f.name AS Country_name,
              c.name AS City
       from cities c
       right join facts f
       on
       f.id = c.facts_id
       where c.id is null
"""

sql_query(q)

                                     Country_name  City
0                                          Kosovo  None
1                                          Monaco  None
2                                           Nauru  None
3                                      San Marino  None
4                                       Singapore  None
5                         Holy See (Vatican City)  None
6                                          Taiwan  None
7                                  European Union  None
8                     Ashmore and Cartier Islands  None
9                                Christmas Island  None
10                        Cocos (Keeling) Islands  None
11                              Coral Sea Islands  None
12              Heard Island and McDonald Islands  None
13                                 Norfolk Island  None
14                                      Hong Kong  None
15                                          Macau  None
16                              Clipperton Island  None
17            French Southern and Antarctic Lands  None
18                               Saint Barthelemy  None
19                                   Saint Martin  None
20                                        Curacao  None
21                                   Sint Maarten  None
22                                   Cook Islands  None
23                                           Niue  None
24                                        Tokelau  None
25                                  Bouvet Island  None
26                                      Jan Mayen  None
27                                       Svalbard  None
28                                       Akrotiri  None
29                 British Indian Ocean Territory  None
30                                       Dhekelia  None
31                                      Gibraltar  None
32                                       Guernsey  None
33                                         Jersey  None
34                                     Montserrat  None
35                               Pitcairn Islands  None
36       South Georgia and South Sandwich Islands  None
37                                 Navassa Island  None
38                                    Wake Island  None
39  United States Pacific Island Wildlife Refuges  None
40                                     Antarctica  None
41                                     Gaza Strip  None
42                                Paracel Islands  None
43                                Spratly Islands  None
44                                      West Bank  None
45                                   Arctic Ocean  None
46                                 Atlantic Ocean  None
47                                   Indian Ocean  None
48                                  Pacific Ocean  None
49                                 Southern Ocean  None
50                                          World  None

In [25]:
q = """SELECT 
           f.name AS Country_name,
           c.name AS City,
           c.population AS City_population
       FROM facts f
       INNER JOIN cities c
       ON 
       f.id = c.facts_id
       WHERE c.population > 10000000
"""

sql_query(q)

     Country_name                              City  City_population
0       Argentina                      Buenos Aires         13528000
1      Bangladesh                             Dhaka         15391000
2          Brazil                         Sao Paulo         19924000
3           China                          Shanghai         20208000
4           China                           Beijing         15594000
5           China                         Guangzhou         10849000
6           Egypt                             Cairo         11169000
7          France         Marseille-Aix-en-Provence         14890100
8           India                         New Delhi         22654000
9           India                            Mumbai         19744000
10          India                           Kolkata         14402000
11          Japan                             Tokyo         37217000
12          Japan                        Osaka-Kobe         11494000
13         Mexico                       Mexico City         20446000
14        Nigeria                             Lagos         11223000
15       Pakistan                           Karachi         13876000
16    Philippines                            Manila         11862000
17         Russia                            Moscow         11621000
18         Turkey                          Istanbul         11253000
19  United States                   New York-Newark         20352000
20  United States  Los Angeles-Long Beach-Santa Ana         13395000

In [26]:
q = """select f.name Country_name, c.name City from facts f
       inner join cities c
       on
       f.id == c.facts_id
       where f.name == "United Arab Emirates" 
    

"""
sql_query(q)

           Country_name       City
0  United Arab Emirates  Abu Dhabi
1  United Arab Emirates      Dubai
2  United Arab Emirates    Sharjah

In [30]:
q = """select f.name country_name, c.name city_name, c.population  City_population
      
"""

sql_query(q)

DatabaseError: Execution failed on sql 'SELECT
           f.name AS Country_name,
           c.name AS City,
           c.population AS City_population
       FROM facts f
       INNER JOIN cities c
       ON f.id = c.facts_id
       WHERE f.capital = 0
       AND c.population > 10000000
       ORDER BY c.population DESC
       LIMIT 3
': no such column: f.capital